export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_BY_VALUE = "INCREMENT_BY_VALUE";

export const INIT_ACCOUNT_PENDING = "INIT_ACCOUNT_PENDING";
export const INIT_ACCOUNT_SUCCESS = "INIT_ACCOUNT_SUCCESS";
export const INIT_ACCOUNT_REJECTED = "INIT_ACCOUNT_REJECTED";

export const BONUS_POINTS = "BONUS_POINTS";
